BEGIN;
DROP INDEX IF EXISTS uq_active_doctor_slot;
DROP INDEX IF EXISTS uq_active_patient_slot;
DROP INDEX IF EXISTS uq_active_booking_user_slot;
DROP INDEX IF EXISTS uq_family_patient;
DROP INDEX IF EXISTS idx_users_role_active;
DROP INDEX IF EXISTS idx_appointments_patient;
DROP INDEX IF EXISTS idx_appointments_doctor;
DROP INDEX IF EXISTS idx_otp_lookup;
DROP TABLE IF EXISTS prescription_items CASCADE;
DROP TABLE IF EXISTS prescriptions CASCADE;
DROP TABLE IF EXISTS medicines CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS family_members CASCADE;
DROP TABLE IF EXISTS families CASCADE;
DROP TABLE IF EXISTS otp_codes CASCADE;
DROP TABLE IF EXISTS doctor_availability CASCADE;
DROP TABLE IF EXISTS doctor_profiles CASCADE;
DROP TABLE IF EXISTS patient_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS appointment_status;
DROP TYPE IF EXISTS family_membership_status;
DROP TYPE IF EXISTS otp_purpose;
COMMIT;
