export const listDoctorsSql = `SELECT u.id, u.name, u.email, u.is_active, d.sex, d.speciality, COALESCE(json_agg(json_build_object('weekday', a.weekday, 'start_time', to_char(a.start_time,'HH24:MI'), 'end_time', to_char(a.end_time,'HH24:MI')) ORDER BY a.weekday,a.start_time) FILTER (WHERE a.id IS NOT NULL), '[]'::json) AS availability FROM users u JOIN doctor_profiles d ON d.user_id = u.id LEFT JOIN doctor_availability a ON a.doctor_id = u.id WHERE u.role = $1 GROUP BY u.id,d.sex,d.speciality ORDER BY u.name`;
export const getDoctorByIdSql = `SELECT u.id, u.name, u.email, u.is_active, d.sex, d.speciality FROM users u JOIN doctor_profiles d ON d.user_id = u.id WHERE u.id = $1 AND u.role = $2 LIMIT 1`;
export const insertDoctorProfileSql = `INSERT INTO doctor_profiles (user_id, sex, speciality) VALUES ($1,$2,$3)`;
export const insertDoctorAvailabilitySql = `INSERT INTO doctor_availability (id, doctor_id, weekday, start_time, end_time) VALUES ($1,$2,$3,$4,$5)`;
export const clearDoctorAvailabilitySql = `DELETE FROM doctor_availability WHERE doctor_id = $1`;
export const updateDoctorProfileSql = `UPDATE doctor_profiles SET sex = $2, speciality = $3, updated_at = now() WHERE user_id = $1`;
export const updateDoctorUserSql = `UPDATE users SET name = $2, email = $3, password_hash = COALESCE($4,password_hash), updated_at = now() WHERE id = $1 RETURNING id, name, email, role, is_active`;
export const setDoctorActiveSql = `UPDATE users SET is_active = $2, updated_at = now() WHERE id = $1 AND role = $3 RETURNING id,is_active`;
export const listPatientsSelectSql = `SELECT id, name, email FROM users WHERE role = $1 AND is_active = $2 ORDER BY name`;
export const getAppointmentForRescheduleSql = `SELECT a.id, a.patient_id, a.beneficiary_patient_id, a.doctor_id, a.appointment_date, to_char(a.slot_start,'HH24:MI') AS slot_start, a.status FROM appointments a WHERE a.id = $1 AND a.doctor_id = $2 AND a.beneficiary_patient_id = $3 AND a.appointment_date >= ((CURRENT_TIMESTAMP AT TIME ZONE $5)::date) AND a.status = ANY($4) LIMIT 1`;
export const getDoctorDayAvailabilitySql = `SELECT to_char(start_time,'HH24:MI') AS start_time, to_char(end_time,'HH24:MI') AS end_time FROM doctor_availability WHERE doctor_id = $1 AND weekday = $2 ORDER BY start_time`;
export const getDoctorBookedSlotsSql = `SELECT to_char(slot_start,'HH24:MI') AS slot_start FROM appointments WHERE doctor_id = $1 AND appointment_date = $2 AND status = ANY($3)`;
export const getPatientBookedSlotsSql = `SELECT to_char(slot_start,'HH24:MI') AS slot_start FROM appointments WHERE beneficiary_patient_id = $1 AND appointment_date = $2 AND status = ANY($3)`;
export const updateAppointmentRescheduleSql = `UPDATE appointments SET appointment_date = $2, slot_start = $3, slot_end = $4, status = $5, updated_at = now() WHERE id = $1 RETURNING id, appointment_date, to_char(slot_start,'HH24:MI') AS slot_start, to_char(slot_end,'HH24:MI') AS slot_end, status`;
export const getAppointmentContactSql = `SELECT a.id, a.room_id, pu.name AS patient_name, pu.email AS patient_email, du.name AS doctor_name, du.email AS doctor_email, to_char(a.appointment_date,'YYYY-MM-DD') AS appointment_date, to_char(a.slot_start,'HH24:MI') AS slot_start FROM appointments a JOIN users pu ON pu.id = a.beneficiary_patient_id JOIN users du ON du.id = a.doctor_id WHERE a.id = $1 LIMIT 1`;

export const listUpcomingForPatientDoctorSql = `SELECT a.id,a.patient_id,a.beneficiary_patient_id,to_char(a.appointment_date,'YYYY-MM-DD') AS appointment_date,to_char(a.slot_start,'HH24:MI') AS slot_start,a.status,bu.name AS beneficiary_name FROM appointments a JOIN users bu ON bu.id=a.beneficiary_patient_id WHERE a.beneficiary_patient_id=$1 AND a.doctor_id=$2 AND a.appointment_date>=((CURRENT_TIMESTAMP AT TIME ZONE $4)::date) AND a.status=ANY($3) ORDER BY a.appointment_date,a.slot_start`;

export const bookingUserBookedSlotsSql = `SELECT to_char(slot_start,'HH24:MI') AS slot_start FROM appointments WHERE patient_id = $1 AND appointment_date = $2 AND status = ANY($3)`;
