export const getFamilySql = `SELECT f.id AS family_id, f.name AS family_name, f.owner_patient_id, fm.id AS membership_id, fm.patient_id, fm.status, u.name AS patient_name, u.email AS patient_email FROM families f JOIN family_members fm ON fm.family_id = f.id JOIN users u ON u.id = fm.patient_id WHERE f.id IN (SELECT family_id FROM family_members WHERE patient_id = $1) ORDER BY f.name, u.name`;
export const findPatientByEmailSql = `SELECT id, name, email FROM users WHERE lower(email) = lower($1) AND role = $2 AND is_active = $3 LIMIT 1`;
export const createFamilySql = `INSERT INTO families (id, name, owner_patient_id) VALUES ($1,$2,$3) RETURNING id,name`;
export const addFamilyMemberSql = `INSERT INTO family_members (id, family_id, patient_id, status, invited_by) VALUES ($1,$2,$3,$4,$5) RETURNING id`;
export const getFamilyMembershipForPatientSql = `SELECT fm.family_id, fm.id, f.name, fm.status FROM family_members fm JOIN families f ON f.id = fm.family_id WHERE fm.patient_id = $1 ORDER BY fm.created_at DESC LIMIT 1`;
export const updateFamilyInviteSql = `UPDATE family_members SET status = $2, responded_at = now() WHERE id = $1 AND patient_id = $3 RETURNING id,family_id,status`;
export const listFamilyMembersForBookingSql = `SELECT u.id,u.name,u.email FROM family_members fm JOIN users u ON u.id = fm.patient_id WHERE fm.family_id = $1 AND fm.status = $2 ORDER BY u.name`;
export const listActiveDoctorsSql = `SELECT u.id,u.name,d.speciality FROM users u JOIN doctor_profiles d ON d.user_id=u.id WHERE u.role=$1 AND u.is_active=$2 ORDER BY u.name`;
export const insertAppointmentSql = `WITH inserted AS (INSERT INTO appointments (id, patient_id, beneficiary_patient_id, doctor_id, appointment_date, slot_start, slot_end, status, room_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *) SELECT i.id,i.room_id,i.patient_id,i.beneficiary_patient_id,i.doctor_id,i.appointment_date,to_char(i.slot_start,'HH24:MI') AS slot_start,to_char(i.slot_end,'HH24:MI') AS slot_end,i.status,pu.email AS patient_email,pu.name AS patient_name,du.name AS doctor_name FROM inserted i JOIN users pu ON pu.id=i.patient_id JOIN users du ON du.id=i.doctor_id`;
export const listAppointmentsPatientSql = `SELECT a.id,a.appointment_date,to_char(a.slot_start,'HH24:MI') AS slot_start,to_char(a.slot_end,'HH24:MI') AS slot_end,a.status,a.room_id,du.name AS doctor_name,d.speciality,bu.name AS beneficiary_name,pres.id AS prescription_id FROM appointments a JOIN users du ON du.id=a.doctor_id JOIN doctor_profiles d ON d.user_id=du.id JOIN users bu ON bu.id=a.beneficiary_patient_id LEFT JOIN prescriptions pres ON pres.appointment_id=a.id WHERE a.patient_id=$1 ORDER BY a.appointment_date DESC,a.slot_start DESC`;
export const listAppointmentsDoctorSql = `SELECT a.id,a.appointment_date,to_char(a.slot_start,'HH24:MI') AS slot_start,to_char(a.slot_end,'HH24:MI') AS slot_end,a.status,pu.name AS patient_name,bu.name AS beneficiary_name,pu.email AS patient_email FROM appointments a JOIN users pu ON pu.id=a.patient_id JOIN users bu ON bu.id=a.beneficiary_patient_id WHERE a.doctor_id=$1 ORDER BY a.appointment_date DESC,a.slot_start DESC`;
export const cancelAppointmentSql = `UPDATE appointments SET status=$2, updated_at=now() WHERE id=$1 AND patient_id=$3 AND appointment_date >= ((CURRENT_TIMESTAMP AT TIME ZONE $5)::date) AND status = ANY($4) RETURNING id,status`;
export const getAppointmentForPatientSql = `SELECT a.id,a.patient_id,a.beneficiary_patient_id,a.doctor_id,a.appointment_date,to_char(a.slot_start,'HH24:MI') AS slot_start,a.status,pu.name AS patient_name,pu.email AS patient_email,pu.date_of_birth AS patient_dob,du.name AS doctor_name FROM appointments a JOIN users pu ON pu.id=a.patient_id JOIN users du ON du.id=a.doctor_id WHERE a.id=$1 AND a.patient_id=$2 LIMIT 1`;
export const insertPrescriptionSql = `INSERT INTO prescriptions (id, appointment_id, doctor_id, patient_id, beneficiary_patient_id, prescription_date, age, pdf_url) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`;
export const insertPrescriptionItemSql = `INSERT INTO prescription_items (id,prescription_id,medicine_name,dose,condition_note,morning,afternoon,evening,night,sos,food_timing) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`;
export const markAppointmentCompletedSql = `UPDATE appointments SET status=$2, updated_at=now() WHERE id=$1 AND doctor_id=$3 RETURNING id,status`;
export const getPrescriptionByAppointmentSql = `SELECT p.id,p.pdf_url,p.prescription_date,p.age,pu.name AS patient_name,du.name AS doctor_name,dp.speciality FROM prescriptions p JOIN users pu ON pu.id=p.beneficiary_patient_id JOIN users du ON du.id=p.doctor_id JOIN doctor_profiles dp ON dp.user_id=du.id WHERE p.appointment_id=$1 LIMIT 1`;
export const searchMedicinesSql = `SELECT id,name FROM medicines WHERE name ILIKE $1 ORDER BY name LIMIT $2`;
export const getTodayPatientsForDoctorSql = `SELECT a.id AS appointment_id,a.beneficiary_patient_id AS patient_id,bu.name AS patient_name,bu.email,bu.date_of_birth FROM appointments a JOIN users bu ON bu.id=a.beneficiary_patient_id WHERE a.doctor_id=$1 AND a.appointment_date=((CURRENT_TIMESTAMP AT TIME ZONE $3)::date) AND a.status = ANY($2) ORDER BY a.slot_start`;
export const getPrescriptionItemsSql = `SELECT medicine_name,dose,condition_note,morning,afternoon,evening,night,sos,food_timing FROM prescription_items WHERE prescription_id=$1 ORDER BY created_at`;
export const getPrescriptionDataSql = `SELECT p.id,p.prescription_date,p.age,pu.name AS patient_name,du.name AS doctor_name,dp.speciality FROM prescriptions p JOIN users pu ON pu.id=p.beneficiary_patient_id JOIN users du ON du.id=p.doctor_id JOIN doctor_profiles dp ON dp.user_id=du.id WHERE p.id=$1 AND p.doctor_id=$2 LIMIT 1`;

export const familyInviteContactSql = `SELECT inv.name AS inviter_name, inv.email AS inviter_email, invitee.name AS invitee_name, invitee.email AS invitee_email FROM family_members fm JOIN users inv ON inv.id=fm.invited_by JOIN users invitee ON invitee.id=fm.patient_id WHERE fm.id=$1 LIMIT 1`;

export const getAppointmentForDoctorSql = `SELECT a.id,a.patient_id,a.beneficiary_patient_id,a.doctor_id,a.appointment_date,to_char(a.slot_start,'HH24:MI') AS slot_start,a.status,pu.name AS patient_name,pu.email AS patient_email,pu.date_of_birth AS patient_dob,du.name AS doctor_name FROM appointments a JOIN users pu ON pu.id=a.patient_id JOIN users du ON du.id=a.doctor_id WHERE a.id=$1 AND a.doctor_id=$2 LIMIT 1`;
